# Cloud Run sets PORT=8080; ensure the app listens on it
server.port=${PORT:8080}

# Disable dev tools and verbose logging
spring.graphql.graphiql.enabled=true
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

spring.datasource.driver-class-name=org.postgresql.Driver
